FROM node:24-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:24-alpine
ENV NODE_ENV=production
WORKDIR /app
# "simpler": take the whole build folder
COPY --from=build /app ./
USER node
EXPOSE 3000
CMD ["node", "dist/server.js"]
