"""Generate docs/command-reference.md, labs/README.md and troubleshooting/README.md from the lessons.

The command reference lists every Docker command the course runs: what it does, the flags the course uses (with their
meaning) and the lessons that use it, the first one being the lesson that teaches it.

    python tools/command_reference.py           write the files
    python tools/command_reference.py --check   fail if a file is out of date (CI)
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "<!-- generated by tools/command_reference.py from the lessons: edit the lessons, then regenerate -->\n"

# command → (area, what it does). Only these are listed; anything else in a lesson is a typo on purpose or an argument.
COMMANDS = {
    "run": ("Containers", "create and start a container from an image"),
    "create": ("Containers", "create a container without starting it"),
    "start": ("Containers", "start stopped containers"),
    "stop": ("Containers", "stop running containers gracefully (SIGTERM, then SIGKILL after a timeout)"),
    "restart": ("Containers", "stop and start containers"),
    "kill": ("Containers", "send a signal (default SIGKILL) to a container's main process"),
    "pause": ("Containers", "freeze every process of a container"),
    "unpause": ("Containers", "resume a paused container"),
    "rm": ("Containers", "remove containers"),
    "rename": ("Containers", "rename a container"),
    "ps": ("Containers", "list containers (running only, or all with -a)"),
    "container ls": ("Containers", "list containers (same as docker ps)"),
    "container create": ("Containers", "create a container without starting it"),
    "container start": ("Containers", "start stopped containers"),
    "container rm": ("Containers", "remove containers"),
    "container inspect": ("Containers", "low-level details of containers as JSON"),
    "container diff": ("Containers", "files added (A), changed (C) or deleted (D) in a container's writable layer"),
    "container prune": ("Containers", "remove all stopped containers"),
    "update": ("Containers", "change resource limits or the restart policy of a running container"),
    "wait": ("Containers", "block until containers stop, then print their exit codes"),
    "logs": ("Inspecting and debugging", "a container's standard output and standard error"),
    "exec": ("Inspecting and debugging", "run a command in a running container"),
    "inspect": ("Inspecting and debugging", "low-level details of any object (container, image, network, volume) as JSON"),
    "port": ("Inspecting and debugging", "a container's published ports"),
    "top": ("Inspecting and debugging", "the processes running in a container"),
    "diff": ("Inspecting and debugging", "changes in a container's writable layer"),
    "cp": ("Inspecting and debugging", "copy files between a container and the host"),
    "stats": ("Inspecting and debugging", "live CPU, memory, network and I/O use of containers"),
    "events": ("Inspecting and debugging", "the engine's real-time event stream (create, start, die, health, …)"),
    "attach": ("Inspecting and debugging", "attach the terminal to a running container's main process"),
    "commit": ("Images", "create an image from a container's changes (for investigation, not for production)"),
    "build": ("Images", "build an image from a Dockerfile and a build context"),
    "pull": ("Images", "download an image from a registry"),
    "push": ("Images", "upload an image to a registry"),
    "tag": ("Images", "give an image an additional name (repository:tag)"),
    "history": ("Images", "the layers of an image and the instruction that created each one"),
    "images": ("Images", "list images (same as docker image ls)"),
    "save": ("Images", "write images to a tar archive"),
    "load": ("Images", "read images from a tar archive"),
    "image ls": ("Images", "list images"),
    "image pull": ("Images", "download an image from a registry"),
    "image push": ("Images", "upload an image to a registry"),
    "image rm": ("Images", "remove images"),
    "image inspect": ("Images", "an image's configuration and layers as JSON"),
    "image history": ("Images", "the layers of an image and the instruction that created each one"),
    "image tag": ("Images", "give an image an additional name"),
    "image prune": ("Images", "remove dangling images (all unused with -a)"),
    "image save": ("Images", "write images to a tar archive"),
    "image load": ("Images", "read images from a tar archive"),
    "buildx build": ("Builds", "build with BuildKit: multi-platform, cache import/export, --push"),
    "buildx ls": ("Builds", "list builders and the platforms they support"),
    "buildx create": ("Builds", "create a builder (for example one that can build several platforms)"),
    "buildx use": ("Builds", "make a builder the default"),
    "buildx rm": ("Builds", "remove a builder"),
    "buildx inspect": ("Builds", "details of a builder"),
    "buildx imagetools": ("Builds", "inspect or create multi-platform image indexes in a registry"),
    "buildx prune": ("Builds", "remove the build cache"),
    "builder prune": ("Builds", "remove the build cache"),
    "network create": ("Networks", "create a network"),
    "network ls": ("Networks", "list networks"),
    "network inspect": ("Networks", "a network's configuration and attached containers"),
    "network connect": ("Networks", "attach a running container to a network"),
    "network disconnect": ("Networks", "detach a container from a network"),
    "network rm": ("Networks", "remove networks"),
    "network prune": ("Networks", "remove unused networks"),
    "volume create": ("Volumes", "create a named volume"),
    "volume ls": ("Volumes", "list volumes"),
    "volume inspect": ("Volumes", "a volume's driver, mount point and labels"),
    "volume rm": ("Volumes", "remove volumes (and their data)"),
    "volume prune": ("Volumes", "remove unused volumes (and their data)"),
    "compose up": ("Docker Compose", "create and start the services of a Compose project"),
    "compose down": ("Docker Compose", "stop and remove the project's containers and networks (volumes with -v)"),
    "compose ps": ("Docker Compose", "the project's containers and their state"),
    "compose logs": ("Docker Compose", "the logs of the project's services"),
    "compose exec": ("Docker Compose", "run a command in a running service container"),
    "compose run": ("Docker Compose", "run a one-off command in a new service container"),
    "compose build": ("Docker Compose", "build the services' images"),
    "compose config": ("Docker Compose", "validate the Compose file and print it fully resolved"),
    "compose start": ("Docker Compose", "start the project's existing containers"),
    "compose stop": ("Docker Compose", "stop the project's containers without removing them"),
    "compose restart": ("Docker Compose", "restart services"),
    "compose pull": ("Docker Compose", "pull the services' images"),
    "compose push": ("Docker Compose", "push the services' images"),
    "compose images": ("Docker Compose", "the images the project's containers use"),
    "compose top": ("Docker Compose", "the processes of each service"),
    "compose kill": ("Docker Compose", "send a signal to service containers"),
    "compose rm": ("Docker Compose", "remove stopped service containers"),
    "compose ls": ("Docker Compose", "list Compose projects"),
    "compose version": ("Docker Compose", "the Compose version"),
    "compose watch": ("Docker Compose", "rebuild or sync services when files change"),
    "login": ("Registries", "log in to a registry"),
    "logout": ("Registries", "remove a registry's stored credentials"),
    "manifest inspect": ("Registries", "an image's manifest in a registry, without pulling it"),
    "scout cves": ("Security", "known vulnerabilities (CVEs) in an image's packages"),
    "scout quickview": ("Security", "a summary of an image's vulnerabilities"),
    "version": ("Engine and system", "client and server versions"),
    "info": ("Engine and system", "engine configuration and state"),
    "context ls": ("Engine and system", "the engines this client can talk to"),
    "context show": ("Engine and system", "the active context"),
    "context use": ("Engine and system", "switch the active context"),
    "context create": ("Engine and system", "add an engine endpoint (for example ssh://user@host)"),
    "system df": ("Engine and system", "disk space used by images, containers, volumes and build cache"),
    "system prune": ("Engine and system", "remove stopped containers, unused networks, dangling images and build cache"),
    "system events": ("Engine and system", "the engine's event stream"),
    "system info": ("Engine and system", "engine configuration and state"),
}
AREAS = ["Containers", "Inspecting and debugging", "Images", "Builds", "Networks", "Volumes", "Docker Compose",
         "Registries", "Security", "Engine and system"]

# the meaning of the flags the course uses most (command-specific first, then general)
FLAGS = {
    ("run", "-d"): "run in the background (detached)", ("run", "-p"): "publish HOST:CONTAINER port",
    ("run", "--rm"): "remove the container when it stops", ("run", "--name"): "give the container a name",
    ("run", "-e"): "set an environment variable", ("run", "--env-file"): "read environment variables from a file",
    ("run", "-v"): "mount a volume or bind mount", ("run", "--mount"): "mount, explicit syntax",
    ("run", "--network"): "connect to a network", ("run", "-it"): "interactive terminal",
    ("run", "-u"): "run as this user", ("run", "--user"): "run as this user",
    ("run", "--read-only"): "read-only root file system", ("run", "--tmpfs"): "a writable in-memory folder",
    ("run", "--cap-drop"): "remove Linux capabilities", ("run", "--cap-add"): "add Linux capabilities",
    ("run", "--memory"): "memory limit", ("run", "-m"): "memory limit", ("run", "--cpus"): "CPU limit",
    ("run", "--restart"): "restart policy", ("run", "--entrypoint"): "replace the image's ENTRYPOINT",
    ("run", "-w"): "working directory", ("run", "--health-cmd"): "healthcheck command",
    ("run", "--security-opt"): "security options (no-new-privileges, …)", ("run", "--pids-limit"): "process limit",
    ("run", "--label"): "add a label", ("run", "-l"): "add a label", ("run", "--log-driver"): "logging driver",
    ("run", "--log-opt"): "logging driver option", ("run", "--init"): "run an init process as PID 1",
    ("run", "--platform"): "run an image for this platform", ("run", "--sysctl"): "set a namespaced kernel setting",
    ("build", "-t"): "name:tag of the image", ("build", "-f"): "Dockerfile path",
    ("build", "--build-arg"): "set a build argument (ARG)", ("build", "--target"): "build up to this stage",
    ("build", "--no-cache"): "ignore the build cache", ("build", "-q"): "print only the image ID",
    ("build", "--progress"): "build output style (plain shows every step)", ("build", "--secret"): "a build secret",
    ("ps", "-a"): "include stopped containers", ("ps", "-q"): "IDs only", ("ps", "--filter"): "filter",
    ("ps", "--format"): "Go template output", ("logs", "-f"): "follow", ("logs", "--tail"): "last N lines",
    ("logs", "--since"): "only newer than", ("logs", "-t"): "timestamps", ("exec", "-it"): "interactive terminal",
    ("exec", "-u"): "run as this user", ("exec", "-e"): "set an environment variable",
    ("rm", "-f"): "stop and remove", ("rm", "-v"): "also remove anonymous volumes",
    ("stats", "--no-stream"): "print once", ("events", "--since"): "from this time", ("events", "--until"): "until",
    ("events", "--filter"): "filter", ("stop", "-t"): "seconds before SIGKILL",
    ("compose up", "-d"): "in the background", ("compose up", "--build"): "build images first",
    ("compose up", "--wait"): "wait until services are running/healthy", ("compose down", "-v"): "also remove volumes",
    ("compose down", "--rmi"): "also remove images", ("compose logs", "-f"): "follow",
    ("compose exec", "-T"): "no terminal (for scripts)", ("compose", "-f"): "Compose file",
    ("compose", "-p"): "project name", ("compose", "--profile"): "enable a profile",
    ("compose", "--env-file"): "variables file", ("image ls", "--filter"): "filter (dangling=true, …)",
    ("image prune", "-a"): "all unused images, not only dangling", ("image rm", "-f"): "force",
    ("buildx build", "--platform"): "target platforms", ("buildx build", "--push"): "push the result",
    ("buildx build", "--load"): "load the result into the engine", ("buildx build", "--cache-from"): "import cache",
    ("buildx build", "--cache-to"): "export cache", ("network create", "--driver"): "network driver",
    ("network create", "--internal"): "no outside access", ("network create", "--subnet"): "subnet",
    ("login", "-u"): "user name", ("login", "--password-stdin"): "read the password from standard input",
    ("volume prune", "-a"): "also named volumes", ("pull", "-q"): "quiet", ("push", "-q"): "quiet",
    ("inspect", "--format"): "Go template output", ("inspect", "-f"): "Go template output",
    ("update", "--memory"): "memory limit", ("update", "--cpus"): "CPU limit",
    ("exec", "-d"): "in the background", ("exec", "-i"): "keep standard input open", ("exec", "-w"): "working directory",
    ("ps", "--no-trunc"): "full IDs and commands", ("ps", "-s"): "writable layer size",
    ("container ls", "-s"): "writable layer size", ("build", "--check"): "lint the Dockerfile without building",
    ("build", "--pull"): "pull a newer base image first", ("compose up", "--scale"): "run N containers of a service",
    ("compose up", "--force-recreate"): "recreate containers even if unchanged",
    ("compose up", "--no-deps"): "do not start linked services", ("compose up", "--quiet-build"): "hide build output",
    ("compose up", "--remove-orphans"): "remove containers of services no longer in the file",
    ("compose ps", "-a"): "include stopped containers", ("compose ps", "--format"): "Go template output",
    ("compose config", "--quiet"): "only validate", ("compose config", "--services"): "list the service names",
    ("compose logs", "--no-log-prefix"): "without the service-name prefix", ("compose build", "--no-cache"): "ignore the cache",
    ("run", "-i"): "keep standard input open", ("run", "-t"): "allocate a terminal", ("run", "--pull"): "pull policy",
    ("run", "--cpu-shares"): "relative CPU weight", ("run", "--memory-swap"): "memory + swap limit",
    ("run", "--oom-kill-disable"): "do not kill on out-of-memory", ("run", "--health-interval"): "time between checks",
    ("run", "--dns"): "DNS server", ("run", "--hostname"): "container host name", ("run", "--add-host"): "add a hosts entry",
    ("run", "-P"): "publish all exposed ports to random host ports", ("run", "--expose"): "document a port",
    ("run", "--privileged"): "every capability and device: never in production",
    ("logs", "--timestamps"): "timestamps", ("logs", "--until"): "only older than", ("logs", "--follow"): "follow",
    ("history", "--no-trunc"): "full instructions", ("history", "--format"): "Go template output",
    ("tag", "-f"): "force", ("events", "--format"): "Go template output", ("stats", "--format"): "Go template output",
}
GENERAL_FLAGS = {"--format": "Go template output", "-f": "force", "-q": "quiet / IDs only", "--filter": "filter",
                 "-a": "all"}

LESSON_GLOBS = ["[0-2][0-9]-*/[0-9][0-9][0-9]-*/README.md", "[0-2][0-9]-*/assessment.md",
                "17-troubleshooting/[0-9][0-9]-*/README.md", "21-projects/[0-9][0-9]-*/README.md",
                "22-capstone/README.md", "22-capstone/final-exam/SOLUTION.md"]


def sources() -> list[Path]:
    files = {p for g in LESSON_GLOBS for p in ROOT.glob(g)}
    return sorted(files, key=lambda p: p.relative_to(ROOT).as_posix())


def label(md: Path) -> str:
    rel = md.relative_to(ROOT).as_posix()
    if m := re.match(r"\d\d-[^/]+/(\d{3})-", rel):
        return m.group(1)
    if m := re.match(r"17-troubleshooting/(\d\d)-", rel):
        return f"T{m.group(1)}"
    if m := re.match(r"21-projects/(\d\d)-", rel):
        return f"P{m.group(1)}"
    if rel.endswith("assessment.md"):
        return f"A{rel[:2]}"
    return "exam" if "final-exam" in rel else "capstone"


def title(md: Path) -> str:
    return re.search(r"^# (.+)$", md.read_text(encoding="utf-8"), re.M).group(1)


INVOCATION = re.compile(r"(?:^|[\s(;|&`])docker\s+([^|;&\n`)]*)")


# options that take no value: everything else is followed by its value (unless written --flag=value)
BOOLEAN = {"--rm", "-d", "-i", "-t", "-it", "-ti", "--read-only", "--init", "--privileged", "-a", "-q", "-f", "-P",
           "--no-stream", "--build", "--wait", "-T", "--no-cache", "--pull", "--push", "--load", "--detach",
           "--interactive", "--tty", "--quiet", "--no-deps", "--force-recreate", "--remove-orphans", "--no-trunc",
           "--all", "--force", "-s", "--size", "--follow", "--timestamps", "--no-log-prefix", "--no-color",
           "--password-stdin", "--dry-run", "--quiet-pull", "--services", "--volumes", "-v"}
# commands whose first positional argument (the image or container) ends the options: what follows belongs to the
# command run inside the container
POSITIONAL_ENDS = {"run", "create", "exec", "container create", "compose run", "compose exec"}


def option_flags(cmd: str, args: list[str]) -> set[str]:
    flags, skip = set(), False
    for a in args:
        if skip:
            skip = False
            continue
        if re.match(r"^--?[a-zA-Z]", a):
            name = a.split("=")[0]
            if re.fullmatch(r"-[a-zA-Z]{2,}", name) and name not in ("-it", "-ti"):
                flags.update(f"-{c}" for c in name[1:])          # -aq → -a -q
            else:
                flags.add(name)
            skip = "=" not in a and name not in BOOLEAN and not re.fullmatch(r"-[a-zA-Z]{2,}", name)
            if cmd in ("run", "create", "container create", "compose run") and name == "-v":
                skip = True                                      # -v HOST:CONTAINER takes a value for run
        elif cmd in POSITIONAL_ENDS:
            break
    return flags


def parse(text: str):
    """Yield (command, flags) for every docker invocation in the ```bash blocks."""
    for block in re.findall(r"^```bash\n(.*?)^```", text, re.M | re.S):
        block = re.sub(r"\\\n\s*", " ", block)
        for m in INVOCATION.finditer(block):
            words = m.group(1).split()
            # global options before the command (docker compose -p NAME up, docker --context X ps)
            i, globals_ = 0, []
            if words[:1] == ["compose"]:
                i = 1
                while i < len(words) and words[i].startswith("-"):
                    globals_.append(words[i].split("=")[0])
                    i += 2 if "=" not in words[i] and words[i] in ("-f", "-p", "--profile", "--env-file",
                                                                     "--project-directory", "--file") else 1
                head = ["compose"] + words[i:i + 1]
                rest = words[i + 1:]
            else:
                head, rest = words[:2], words[2:]
            two, one = " ".join(head[:2]), " ".join(head[:1])
            cmd = two if two in COMMANDS else one if one in COMMANDS else None
            if not cmd:
                continue
            args = rest if cmd == two else words[1:]
            flags = option_flags(cmd, args)
            if cmd.startswith("compose"):
                yield "compose", set(globals_)
            yield cmd, flags


def build() -> dict[Path, str]:
    uses: dict[str, list[Path]] = defaultdict(list)
    flags: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    files = sources()
    for md in files:
        for cmd, fl in parse(md.read_text(encoding="utf-8")):
            if cmd == "compose":
                for f in fl:
                    flags["compose"][f] += 1
                continue
            if md not in uses[cmd]:
                uses[cmd].append(md)
            for f in fl:
                flags[cmd][f] += 1

    def link(md: Path, text: str) -> str:
        return f"[{text}](../{md.relative_to(ROOT).as_posix()})"

    out = [HEADER, "# Command reference\n",
           "Every Docker command this course runs, grouped by what it works on. For each one: what it does, the flags",
           "the course uses, and where it is used. The **first** link is the lesson that teaches it; the others show it",
           "in use. Numbers are lessons (`012`), `T07` a troubleshooting problem, `P03` a project, `A10` a module",
           "assessment.\n",
           "Every command accepts `--help`: `docker run --help`, `docker compose up --help`.\n",
           "Contents: " + " · ".join(f"[{a}](#{a.lower().replace(' ', '-')})" for a in AREAS) + "\n"]
    for area in AREAS:
        cmds = [c for c, (a, _) in COMMANDS.items() if a == area and c in uses]
        if not cmds:
            continue
        out.append(f"## {area}\n")
        out.append("| Command | What it does | Flags used in the course | Where |\n|---|---|---|---|")
        for cmd in sorted(cmds, key=lambda c: (files.index(uses[c][0]), c)):
            seen = sorted(flags[cmd].items(), key=lambda kv: (-kv[1], kv[0]))[:8]
            fl = ", ".join(f"`{f}` {FLAGS.get((cmd, f), GENERAL_FLAGS.get(f, ''))}".strip() for f, _ in seen)
            where = uses[cmd]
            first = link(where[0], f"**{label(where[0])}** {title(where[0]).split('·', 1)[-1].strip()}")
            more = ", ".join(link(md, label(md)) for md in where[1:9])
            if len(where) > 9:
                more += f" and {len(where) - 9} more"
            out.append(f"| `docker {cmd}` | {COMMANDS[cmd][1]} | {fl or '—'} | {first}"
                       f"{'<br>also ' + more if more else ''} |")
        out.append("")
    if flags["compose"]:
        out.append("Options of `docker compose` itself (before the subcommand): " + ", ".join(
            f"`{f}` {FLAGS.get(('compose', f), '')}".strip() for f in sorted(flags["compose"])) + ".\n")

    lessons = sorted(ROOT.glob("[0-2][0-9]-*/[0-9][0-9][0-9]-*/README.md"))
    labs = [HEADER, "# Labs\n", "Every lesson's hands-on lab, in course order. Each lab starts from the lesson's *Lab setup*",
            "(`bash scripts/lab.sh …`), and running that again resets it.\n", "| Lesson | Lab | Challenge |\n|---|---|---|"]
    trouble = [HEADER, "# Troubleshooting\n",
               "Two places to practise troubleshooting:\n",
               "- [Module 17](../17-troubleshooting/README.md): 25 production-style problems, organized by symptom.",
               "- Every lesson's *Break it → Troubleshoot it → Fix it*, listed below.\n",
               "| Lesson | Troubleshooting exercise |\n|---|---|"]
    for md in lessons:
        d = md.parent.relative_to(ROOT).as_posix()
        name = title(md)
        if (md.parent / "lab.md").exists():
            labs.append(f"| {name} | [lab](../{d}/lab.md) | [challenge](../{d}/challenge.md) |")
        if (md.parent / "troubleshooting.md").exists():
            trouble.append(f"| {name} | [troubleshooting](../{d}/troubleshooting.md) |")
    return {ROOT / "docs/command-reference.md": "\n".join(out).rstrip() + "\n",
            ROOT / "labs/README.md": "\n".join(labs) + "\n",
            ROOT / "troubleshooting/README.md": "\n".join(trouble) + "\n"}


def main() -> int:
    files = build()
    if "--check" in sys.argv:
        stale = [p for p, body in files.items() if not p.exists() or p.read_text(encoding="utf-8") != body]
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)} (run python tools/command_reference.py)")
        return 1 if stale else 0
    for p, body in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8", newline="\n")
    print(f"{len(files)} files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
