"""Write a README.md for every lesson module (01–20, not 17: its problems have their own index): its lessons, the assessment, and the next module.

    python tools/module_readmes.py          (re)generate
    python tools/module_readmes.py --check  fail if a module README is out of date (CI)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAMES = {"02": "Containers"}   # modules that span several levels: the level line of the first lesson is too narrow
HEADER = "<!-- generated by tools/module_readmes.py from the lessons: edit the lessons, then regenerate -->\n"


def build() -> dict[Path, str]:
    modules = sorted(p for p in ROOT.glob("[0-2][0-9]-*") if p.is_dir() and list(p.glob("[0-9][0-9][0-9]-*/README.md")))
    out = {}
    for mod in modules:
        lessons = sorted(mod.glob("[0-9][0-9][0-9]-*/README.md"))
        first = lessons[0].read_text(encoding="utf-8").split("\n")
        level = next((l for l in first if l.startswith("> Level")), "").split("·")
        name = level[1].strip() if len(level) > 1 else mod.name
        name = NAMES.get(mod.name[:2], name)
        number = mod.name[:2]
        rows = []
        minutes = 0
        for lesson in lessons:
            text = lesson.read_text(encoding="utf-8")
            title = re.match(r"# Lesson (\d+) · (.+)", text).groups()
            what = text.split("## What are we learning?", 1)[1].strip().split("\n\n")[0].replace("\n", " ")
            what = re.sub(r"\s+", " ", what)
            if len(what) > 150:
                what = what[:147].rsplit(" ", 1)[0] + "…"
            m = re.search(r"⏱ (\d+) minutes", text)
            minutes += int(m.group(1)) if m else 0
            rows.append(f"| {title[0]} | [{title[1]}]({lesson.parent.name}/README.md) | {what} |")
        # the next part of the course, which may be one without lessons (17-troubleshooting, 21-projects, 22-capstone)
        later = sorted(p for p in ROOT.glob("[0-2][0-9]-*") if p.is_dir() and p.name > mod.name)
        nxt = later[0] if later else None
        nxt_link = (f"[{nxt.name[3:].replace('-', ' ').capitalize()}]({'../' + nxt.name + '/README.md'})" if nxt
                    else "[Projects](../21-projects/README.md)")
        body = (HEADER + f"# Module {number} · {name}\n\n"
                f"> {len(lessons)} lessons · about {minutes} minutes · run every command from the course folder\n\n"
                "| # | Lesson | What you learn |\n|---|---|---|\n" + "\n".join(rows) + "\n\n"
                f"Then test yourself: [assessment](assessment.md) (quiz, practical challenge, troubleshooting challenge, "
                f"real-world scenario).\n\nNext: {nxt_link} · [Course map](../README.md#course-map)\n")
        out[mod / "README.md"] = body
    return out


def main() -> int:
    files = build()
    if "--check" in sys.argv:
        stale = [p for p, body in files.items() if not p.exists() or p.read_text(encoding="utf-8") != body]
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)} (run python tools/module_readmes.py)")
        return 1 if stale else 0
    for p, body in files.items():
        p.write_text(body, encoding="utf-8", newline="\n")
    print(f"{len(files)} module READMEs written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
